version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    restart: unless-stopped
    networks:
      - rekov_net

  frontend:
    build:
      context: ./rekoviu
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rekov_net

networks:
  rekov_net:
    driver: bridge
